### PR TITLE
disturbance stops view creation (issue #22)

### PR DESCRIPTION
**Pull request by znmeb**
The code to create two indexes and the materialized view is done. I've tested it on the full TOAD database locally; once the indexes are built, it only takes about two minutes to refresh the view.

I'm uploading the resulting dataset as a CSV file to S3 so the data scientists can look at it and see if things look good. It's about 1 GB - I'll post the link once it's fully updated.

Once we know we have the right columns for the story cards, I'll run the indexing / view creation on the RDS instance and take another backup file.

P.S.: the longitude and latitude values are the same as what's encoded in `geom_point_4326`. I don't know what GIS capabilities the data scientists and front end developers have, so there's redundant information there.

### CODE REVIEW

**Comment by jbeyer16** [comment]
This is nice @znmeb! This is a table of essentially all stop_type = 3 events, from both 2017 and 2018? I think everything we would need is in here, but a couple comments on how we can filter it down specifically for this story card to reduce the size if we want.

The input / filter parameters to the API (@TanviCodeLife do you agree?) are start / end time (15 min intervals between 6 am and 12 pm), months (multi-select from SEP, OCT, NOV), line (10, 14) and potentially day of the week (although originally I thought we only had weekday data anyway, this data set suggests all days of the week). Additionally, we'll know the extent of the map in lat / lon based on the fixed window size. So essentially, we could filter this dataset down by those:
- start_quarter_hour: 6.0 <= x <= 12.0
- end_quarter_hour: 6.0 <= x <= 12.0
- opd_date: in (SEP '17, OCT'17, NOV '17, SEP'18, OCT '18, NOV '18)
- line_id: in (10, 14)
- day of the week: (1,2,3,4,5 for weekdays?) - (this is TBD I think)
- pattern_direction: = 'I' (I assume this means inbound?)
- lat / long / geo: within suggested bounding box (TBD)

Furthermore, we could even drop the act_arr_time and act_dep_time since we have the date and quarter_hour start / end.

At a minimum, the API response then would be just GeoJSON points w/ Lat / Lon and duration as the property for each disturbance stop.

What do you all think?

**Comment by znmeb** [comment]
@jbeyer16 At this point I don't see any reason to drop columns. If you and @TanviCodeLife have everything you need for the story card, I'll load this into the RDS database some time Sunday.

**Comment by TanviCodeLife** [comment]
@jbeyer16 Yes sounds correct to me. 

For sliders:

- start_quarter_hour: 6.0 <= x <= 12.0
- end_quarter_hour: 6.0 <= x <= 12.0
- opd_date: in (SEP '17, OCT'17, NOV '17, SEP'18, OCT '18, NOV '18)

and

For map:

- the API response then would be just GeoJSON points w/ Lat / Lon and duration as the property for each disturbance stop.
- the arcgis data for traffic light from https://opendata.arcgis.com/datasets/9b5ca8086260421d97b427fbd2307d26_54.geojson (Are we expecting this to be incorporated into the transportation API at some point? @znmeb and @jbeyer16 )

I checked with @jaronheard and these are good to start with. Front end team has made some good progress on the slider component. We might be ready next week to add that in to the storycard.

**Comment by znmeb** [comment]
I am planning to load the view into the RDS staging database Sunday. I can also put the traffic signals there when I do. Then I'll give you and Jeff the table name. It will be some lower-case underscore-spaced variant of the shapefile name.

**Pull request merged**
