### PR TITLE
resolves issue #66: remove and ignore staticfiles directory

### PR DESCRIPTION
**Pull request by nam20485**
The files under this directory are re-generated each time the image is built. They should not be checked in to source control.

### CODE REVIEW

**Comment by znmeb** [comment]
I don't know about the rest of the team but I'd like to postpone this till after demo day if possible.

**Comment by jbeyer16** [comment]
Seems pretty straightforward no? Why the need to wait?

**Comment by nam20485** [comment]
As long as we validate that the deploy with the commit removing them
functions correctly, I think it is safe enough.

**Comment by znmeb** [comment]
OK - I'll fire it up once the in-progress merge / deploy cycle for the docs endpoint is live

**Pull request merged**
